import {
  SiPython,
  SiCplusplus,
  SiJavascript,
  SiSolidity,
  SiPytorch,
  SiTensorflow,
  SiReact,
  SiFlask,
  SiFastapi,
  SiRedis,
  SiMysql,
  SiMongodb,
  SiDocker,
  SiLinux,
  SiGit,
  SiOpencv,
  SiHuggingface,
  SiNeo4J,
  SiLangchain,
  SiCoder,
} from 'react-icons/si';
import type { IconType } from 'react-icons';

const skillToIcon: Record<string, IconType> = {
  Python: SiPython,
  'C++': SiCplusplus,
  JavaScript: SiJavascript,
  Solidity: SiSolidity,
  PyTorch: SiPytorch,
  TensorFlow: SiTensorflow,
  Keras: SiTensorflow,
  'scikit-learn': SiPython,
  Gymnasium: SiCoder,
  OpenCV: SiOpencv,
  'Hugging Face': SiHuggingface,
  Hugging: SiHuggingface,
  LangChain: SiLangchain,
  LlamaIndex: SiLangchain,
  LangGraph: SiLangchain,
  'Agentic AI': SiCoder,
  'Applied AI': SiCoder,
  React: SiReact,
  Flask: SiFlask,
  FastAPI: SiFastapi,
  'REST APIs': SiCoder,
  Redis: SiRedis,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  FAISS: SiCoder,
  Pinecone: SiCoder,
  Chroma: SiCoder,
  Weaviate: SiCoder,
  Neo4j: SiNeo4J,
  'AWS Lambda': SiCoder,
  S3: SiCoder,
  AWS: SiCoder,
  Git: SiGit,
  Docker: SiDocker,
  Linux: SiLinux,
};

/** Brand colors for known skills; others use neutral zinc */
const skillToColor: Record<string, string> = {
  Python: '#3776AB',
  'C++': '#00599C',
  JavaScript: '#F7DF1E',
  Solidity: '#363636',
  PyTorch: '#EE4C2C',
  TensorFlow: '#FF6F00',
  Keras: '#D00000',
  'scikit-learn': '#F89939',
  Gymnasium: '#a1a1aa',
  OpenCV: '#5C3EE8',
  'Hugging Face': '#FFD21E',
  LangChain: '#1e88c7',
  LlamaIndex: '#1e88c7',
  LangGraph: '#1e88c7',
  React: '#61DAFB',
  Flask: '#d4d4d8',
  FastAPI: '#009688',
  Redis: '#DC382D',
  MySQL: '#4479A1',
  MongoDB: '#47A248',
  FAISS: '#a1a1aa',
  Pinecone: '#14b8a6',
  Chroma: '#f59e0b',
  Weaviate: '#38bdf8',
  Neo4j: '#4581C3',
  Git: '#F05032',
  Docker: '#2496ED',
  Linux: '#FCC624',
  'Agentic AI': '#a1a1aa',
  'Applied AI': '#a1a1aa',
  'REST APIs': '#a1a1aa',
  'AWS Lambda': '#a1a1aa',
  S3: '#a1a1aa',
  AWS: '#a1a1aa',
};

export function getSkillIcon(skillName: string): IconType {
  return skillToIcon[skillName] ?? SiCoder;
}

export function getSkillColor(skillName: string): string {
  return skillToColor[skillName] ?? '#a1a1aa';
}
